name: CoKeyboard
options:
  bundleIdPrefix: com.cover
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"
  generateEmptyDirectories: true

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  CoKeyboard:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    resources:
      - path: App/Resources/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: App/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/Entitlements/CoKeyboard.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.cover.CoKeyboard
        PRODUCT_NAME: CoKeyboard
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    dependencies:
      - package: WhisperKit
      - target: CoKeyboardExtension
        embed: true
    entitlements:
      path: App/Entitlements/CoKeyboard.entitlements

  CoKeyboardExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: Keyboard
        excludes:
          - "**/.DS_Store"
      - path: Shared
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Keyboard/Resources/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Keyboard/Info.plist
        CODE_SIGN_ENTITLEMENTS: Keyboard/Entitlements/KeyboardExtension.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.cover.CoKeyboard.KeyboardExtension
        PRODUCT_NAME: CoKeyboardExtension
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    dependencies:
      - package: WhisperKit
    entitlements:
      path: Keyboard/Entitlements/KeyboardExtension.entitlements
